### ISSUE TITLE
Fail to access other apps that deployed in micropcf 

### ISSUE THREAD

**Issue by dwu-pivotal** [pivotal-cf/micropcf#13] opened 2016-01-02 10:52 UTC
I've two apps deployed in micropcf, one trying to access the other, but fails with ‘No route to host’

**Comment by davidwadden** [comment] 2016-01-05 17:00
thanks for opening this.  we'll take a look at it.  this one actually ought to work on AWS, but won't on VirtualBox or VMware due to differences in network configuration.

i don't have an estimate when we'll get to this, i have a feeling this is not a quick fix

**Comment by dwu-pivotal** [comment] 2016-01-06 02:26
Looks this is caused by iptables setting in the vm, after I removed two REJECT item in iptables, it works.

**Comment by sclevine** [comment] 2016-01-06 04:43
The following adjustment to the iptables rules should enable container-to-container networking (via the public app route) in microPCF for VMWare and Virtualbox:
```
iptables -D w--input -j REJECT --reject-with icmp-host-prohibited
iptables -A w--input -d 192.168.11.11/32 -p tcp -m tcp --dport 80 -j ACCEPT
iptables -A w--input -d 192.168.11.11/32 -p tcp -m tcp --dport 443 -j ACCEPT
iptables -A w--input -j REJECT --reject-with icmp-host-prohibited
```
(Removing all of the REJECT rules will definitely break security groups and may introduce some unexpected behavior.)

@davidwadden After tracing an app to app connection, this ended up being more simple than I first thought.

**Comment by davidwadden** [comment] 2016-01-12 16:28
@dwu-pivotal our latest [nightly build](https://micropcf.s3.amazonaws.com/nightly/index.html) supports container-to-router and container-to-host network access.  this will allow apps to connect to one another via the router address.  please try that and let us know if you have any issues

**Comment by Sbodiu-pivotal** [comment] 2016-01-14 14:38
@davidwadden I've tested a mongod instance
so my changes were minimal: 
added iptables -A w--input -d 192.168.11.11/32 -p tcp -m tcp --dport 27017 -j ACCEPT
and the on the vbox added port forwarding on 27017 for localhost

**Comment by davidwadden** [comment] 2016-01-14 15:02
thanks @Sbodiu-pivotal, i realized my term "container-to-host" is ambiguous here.  you're running mongodb on your actual physical host (where virtualbox is running), but we enabled traffic to the VM itself (the host from the container POV).

we don't support container-to-host routing and your workaround is appropriate (probably a bit trickier to tweak the `iptables` to allow forwarding to `192.168.11.1`).  i'll change the phrasing on what we've actually enabled to "container-to-vm" routing instead

**Comment by davidwadden** [comment] 2016-01-19 14:52
this was released with [**v0.4.1**](https://github.com/pivotal-cf/micropcf/releases/tag/v0.4.1) -- re-open if this doesn't work!

@davidwadden

**Closed by davidwadden** 2016-01-19 14:52 UTC
